### ISSUE TITLE
How to understand logs

### ISSUE THREAD

**Issue by JerryBian** [adelolmo/hd-idle#22]
After a while of running, I checked the log file, it contains following entries, can you help explain what does it mean?

```
date: 2020-07-28, time: 08:00:25, disk: sdc, running: 600, stopped: 73892
date: 2020-07-28, time: 10:32:22, disk: sdc, running: 601, stopped: 8516
date: 2020-07-29, time: 07:59:57, disk: sdc, running: 601, stopped: 76654
```

I assume the time is for spin up/down, how to know it's up or down?

What does the running/stopped mean?

Thanks.

**Comment by adelolmo** [comment]
These entries are created on disk spin up.
* `running`, seconds the device was running before it spun up the last time.
* `stopped`, seconds since last spin down. This is the time the disk was down before spinning up.

A bit more on `running` explained with an example:
| timestamp | disk spin | event | running | stopped |
| :------------- | :----------: | -----------: | -----------: | -----------: |
| 5:00 | down | disk activity | ? | ? |
| 6:00 | up | go to sleep | - | - |
| 9:00 | down | disk activity | 6:00 - 5:00 = 1h (3600s)  | 9:00 - 6:00 = 3h (10800s) |

Hope it helps.
