### ISSUE TITLE
disk spins up even though reads/writes don't change

### ISSUE THREAD

**Issue by MySurmise** [adelolmo/hd-idle#71]
So I don't know if this is actually an issue with hd-idle or just my drive, but I tried running hd-idle with the -d option to monitor reads and writes and even though they don't change, about 5 minutes after spindown my drive spins up again. 

How can hd-idle not see this and is it somehow possible that my drive spins up without writing to the file hd-idle observes?

**Comment by adelolmo** [comment]
> about 5 minutes after spindown my drive spins up again

Do you mean that the disk spins physically up? or hd-idle reports it as spun up?

> How can hd-idle not see this and is it somehow possible that my drive spins up without writing to the file hd-idle observes?

Since the version 1.14 hd-idle relies on the partitions to determine disk activity. It might be that whatever is spinning it up does not modify the partition read/writes, but it does change the disk read/writes. In that case hd-idle won't see it.
